### ISSUE TITLE
Optimize image grid image loading

### ISSUE THREAD

**Issue by domoench** [domoench/psxyz#38]
# What

Lighthouse score shows we aren't loading optimized image sizes like I thought we were. Will be especially impactful for mobile.

![Screen Shot 2020-09-17 at 3 44 46 PM](https://user-images.githubusercontent.com/2548712/93520612-bfb55300-f8fc-11ea-83b0-807bdc09d0b9.png)

**Comment by inosegbe** [comment]
@Lulu Mu-Park <lulumupark@gmail.com>
See below. Not sure what this means.

-- 
*INYEGUMENA NOSEGBE*    CREATIVE DIRECTOR & ART DIRECTOR    SELECT WORK
<https://www.dropbox.com/s/fihp66fqd3q678b/Nosegbe_SelectWork_Aug2020_Updated.pdf?dl=0>

**Comment by domoench** [comment]
@inosegbe Ah this is just a note to myself to fix something on the implementation, nothing y'all need to do

**Comment by inosegbe** [comment]
LOL sorry!

Ignore this @Lulu Mu-Park <lulumupark@gmail.com>

-- 
*INYEGUMENA NOSEGBE*    CREATIVE DIRECTOR & ART DIRECTOR    SELECT WORK
<https://www.dropbox.com/s/fihp66fqd3q678b/Nosegbe_SelectWork_Aug2020_Updated.pdf?dl=0>

**Comment by domoench** [comment]
Addressed by https://github.com/domoench/psxyz/pull/41
